### ISSUE TITLE
Error writing

### ISSUE THREAD

**Issue by kuklochai** [Ruin0x11/DroidRef#1]
When trying to save, says "Error writing /storage/emulated/0/Pictures/DroidRef/*filename*"

Android 10

**Comment by Ruin0x11** [comment]
Hi. Would you mind checking to see if there's a logcat trace? It should output the exception there.

**Comment by kuklochai** [comment]
> 02-11 00:17:21.789 11817 11817 E MainActivity: Error writing /storage/emulated/0/Pictures/DroidRef/2021-02-11_00-17-20.ref
02-11 00:17:21.789 11817 11817 E MainActivity: java.io.FileNotFoundException: /storage/emulated/0/Pictures/DroidRef/2021-02-11_00-17-20.ref: open failed: EACCES (Permission denied)
02-11 00:17:21.789 11817 11817 E MainActivity: 	at libcore.io.IoBridge.open(IoBridge.java:496)
02-11 00:17:21.789 11817 11817 E MainActivity: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
02-11 00:17:21.789 11817 11817 E MainActivity: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
02-11 00:17:21.789 11817 11817 E MainActivity: 	at com.xiaopo.flying.sticker.StickerViewSerializer.serialize(StickerViewSerializer.kt:120)
02-11 00:17:21.789 11817 11817 E MainActivity: 	at xyz.ruin.droidref.MainActivity.doSave(MainActivity.kt:207)
02-11 00:17:21.789 11817 11817 E MainActivity: 	at xyz.ruin.droidref.MainActivity.access$doSave(MainActivity.kt:44)
02-11 00:17:21.789 11817 11817 E MainActivity: 	at xyz.ruin.droidref.MainActivity$saveAs$1.onClick(MainActivity.kt:182)
02-11 00:17:21.789 11817 11817 E MainActivity: 	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:177)
02-11 00:17:21.789 11817 11817 E MainActivity: 	at android.os.Handler.dispatchMessage(Handler.java:107)
02-11 00:17:21.789 11817 11817 E MainActivity: 	at android.os.Looper.loop(Looper.java:214)
02-11 00:17:21.789 11817 11817 E MainActivity: 	at android.app.ActivityThread.main(ActivityThread.java:7397)
02-11 00:17:21.789 11817 11817 E MainActivity: 	at java.lang.reflect.Method.invoke(Native Method)
02-11 00:17:21.789 11817 11817 E MainActivity: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
02-11 00:17:21.789 11817 11817 E MainActivity: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
02-11 00:17:21.789 11817 11817 E MainActivity: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
02-11 00:17:21.789 11817 11817 E MainActivity: 	at libcore.io.Linux.open(Native Method)
02-11 00:17:21.789 11817 11817 E MainActivity: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
02-11 00:17:21.789 11817 11817 E MainActivity: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
02-11 00:17:21.789 11817 11817 E MainActivity: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
02-11 00:17:21.789 11817 11817 E MainActivity: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7296)
02-11 00:17:21.789 11817 11817 E MainActivity: 	at libcore.io.IoBridge.open(IoBridge.java:482)
02-11 00:17:21.789 11817 11817 E MainActivity: 	... 13 more
![aaw](https://user-images.githubusercontent.com/78849787/107546775-8dc7c480-6bee-11eb-9129-6bf1f82ca23b.jpg)

**Comment by Ruin0x11** [comment]
I think this might be the issue: https://developer.android.com/training/data-storage/use-cases

I checked and my phone I use for testing is running Android 9, which could explain it. I'll try testing with an Android 10 emulator when I can.

**Comment by Ruin0x11** [comment]
Could you see if 217f7e6b535c1b1f2f63e8adb35118d7543cd613 fixes the issue?

**Comment by kuklochai** [comment]
Cleared cache, uninstalled, build and reinstalled, app info shows version 1.0.0. Seems to be the same.

`02-12 02:28:57.042  6248  6248 E MainActivity: Error writing /storage/emulated/0/Pictures/DroidRef/2021-02-12_02-28-56.ref
02-12 02:28:57.042  6248  6248 E MainActivity: java.io.FileNotFoundException: /storage/emulated/0/Pictures/DroidRef/2021-02-12_02-28-56.ref: open failed: EACCES (Permission denied)
02-12 02:28:57.042  6248  6248 E MainActivity: 	at libcore.io.IoBridge.open(IoBridge.java:496)
02-12 02:28:57.042  6248  6248 E MainActivity: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
02-12 02:28:57.042  6248  6248 E MainActivity: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
02-12 02:28:57.042  6248  6248 E MainActivity: 	at com.xiaopo.flying.sticker.StickerViewSerializer.serialize(StickerViewSerializer.kt:120)
02-12 02:28:57.042  6248  6248 E MainActivity: 	at xyz.ruin.droidref.MainActivity.doSave(MainActivity.kt:207)
02-12 02:28:57.042  6248  6248 E MainActivity: 	at xyz.ruin.droidref.MainActivity.access$doSave(MainActivity.kt:44)
02-12 02:28:57.042  6248  6248 E MainActivity: 	at xyz.ruin.droidref.MainActivity$saveAs$1.onClick(MainActivity.kt:182)
02-12 02:28:57.042  6248  6248 E MainActivity: 	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:177)
02-12 02:28:57.042  6248  6248 E MainActivity: 	at android.os.Handler.dispatchMessage(Handler.java:107)
02-12 02:28:57.042  6248  6248 E MainActivity: 	at android.os.Looper.loop(Looper.java:214)
02-12 02:28:57.042  6248  6248 E MainActivity: 	at android.app.ActivityThread.main(ActivityThread.java:7397)
02-12 02:28:57.042  6248  6248 E MainActivity: 	at java.lang.reflect.Method.invoke(Native Method)
02-12 02:28:57.042  6248  6248 E MainActivity: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
02-12 02:28:57.042  6248  6248 E MainActivity: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
02-12 02:28:57.042  6248  6248 E MainActivity: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
02-12 02:28:57.042  6248  6248 E MainActivity: 	at libcore.io.Linux.open(Native Method)
02-12 02:28:57.042  6248  6248 E MainActivity: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
02-12 02:28:57.042  6248  6248 E MainActivity: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
02-12 02:28:57.042  6248  6248 E MainActivity: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
02-12 02:28:57.042  6248  6248 E MainActivity: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7296)
02-12 02:28:57.042  6248  6248 E MainActivity: 	at libcore.io.IoBridge.open(IoBridge.java:482)
02-12 02:28:57.042  6248  6248 E MainActivity: 	... 13 more`

**Comment by kuklochai** [comment]
Sorry, thought I built it, but it was the apk that is lying in the repository. After building it myself the issue was fixed, it now saves properly. Thank you
