### ISSUE TITLE
Error while saving .ref file

### ISSUE THREAD

**Issue by RaduCiucu** [Ruin0x11/DroidRef#2]
I get an error whenever i try to save a board. 
I already gave storage permission to the app for koading images. 

I am runnging the app on OnePlus 6T

**Comment by Ruin0x11** [comment]
I think this is the same as #1, I just forgot to make a new release.

Could you try 1.0.1 at https://github.com/Ruin0x11/DroidRef/releases?

**Comment by RaduCiucu** [comment]
Works perfectly, 
Thank you. 

If you could add text annotations and a donation link it would be great.
