### ISSUE TITLE
Allow toggling the UI to save some space on phones

### ISSUE THREAD

**Issue by 5310** [Ruin0x11/DroidRef#3]
I found your app on the Pureref forums about an Android port, and am very grateful for it 😊 Cross-compatibility or not it already does everything I need and I have faced no stability issues! 

However would you please consider letting us hide the top and bottom buttons bars? On a tablet they're fine, but when using the app to draw on a phone in split-screen view they take up a lot of space. 

Maybe a single button to toggle the UI in one corner like a lot of the painting apps have? Or a hidden gesture like three or four finger tap? What do you think?

**Comment by Ruin0x11** [comment]
Interesting, I hadn't considered that use-case, since I primarily use physical mediums or an external tablet. It should be fairly simple to implement, though.

**Comment by 5310** [comment]
I normally draw on a PC myself; only used to do sketching on the phone when outdoors for studies or when bored. But over the lockdown that went out the window and I got into "virtual" outdoor sketching instead, which is where my use-case comes in 😀. 

Not to rush you, but I would be very much obliged if you added in the toggle in the future. And thanks for the app in the first place too!

**Comment by Ruin0x11** [comment]
I pushed [1.1.0](https://github.com/Ruin0x11/DroidRef/releases/tag/1.1.0) with this feature.

Does it work for you?

**Comment by 5310** [comment]
This is perfect, thank you very much!

**Comment by 5310** [comment]
Just a note: the UI resets to visible anytime the app's "window" resizes. This is not at all a problem when using it, but I'm mentioning it in case it's a bug.
